<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Modules\MenuBuilder\Http\Models\MenuItems;

class MenuItemsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::table('menu_items')->upsert([
            [
                'id' => 49,
                'label' => 'Geo Locale',
                'link' => 'geolocale',
                'params' => '{"permission":"Modules\\\\GeoLocale\\\\Http\\\\Controllers\\\\GeoLocaleController@index", "route_name":["geolocale.index"], "menu_lavel":"1"}',
                'is_default' => 1,
                'icon' => null,
                'parent' => 31,
                'sort' => 58,
                'class' => null,
                'menu' => 1,
                'depth' => 1,
                'is_custom_menu' => 0,
            ],
        ], 'id');


        // DB::table('menu_items')->upsert([
        //     [
        //         'label' => 'Dashboard',
        //         'link' => 'dashboard',
        //         'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\VendorController@index","route_name":["vendor-dashboard"],"menu_level":"3"}',
        //         'is_default' => 1,
        //         'icon' => 'fas fa-home',
        //         'parent' => 0,
        //         'sort' => 0,
        //         'class' => null,
        //         'menu' => 5,
        //         'depth' => 0,
        //         'is_custom_menu' => 0,
        //     ],
        // ], ['menu', 'link']); //



        $menuItems = [
            [
                'label' => 'Dashboard',
                'link' => 'dashboard',
                'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\VendorController@index","route_name":["vendor-dashboard"],"menu_level":"5"}',
                'is_default' => 1,
                'icon' => 'fas fa-home',
                'parent' => 0,
                'sort' => 0,
                'class' => null,
                'menu' => 5,
                'depth' => 0,
                'is_custom_menu' => 0,
            ],
            [
                'label' => 'Orders',
                'link' => 'orders',
                'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\Vendor\\\\VendorOrderController@index", "route_name":["vendorOrder.index", "vendorOrder.view", "vendorOrder.pdf", "vendorOrder.csv"], "menu_level":"5"}',
                'is_default' => 1,
                'icon' => 'fas fa-shopping-bag',
                'parent' => 0,
                'sort' => 2,
                'class' => null,
                'menu' => 5,
                'depth' => 0,
                'is_custom_menu' => 0,
            ],
            [
                'label' => 'Products',
                'link' => 'products',
                'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\Vendor\\\\ProductController@index","route_name":["vendor.products","vendor.product.view","vendor.product.related","vendor.product.search","vendor.product.update","vendor.product.edit", "vendor.product.store", "vendor.product.create", "vendor.product.import", "vendor.itemCsv", "vendor.itemPdf", "vendor.itemDestroy", "vendor.items"]}',
                'is_default' => 1,
                'icon' => 'fas fa-cube',
                'parent' => 0,
                'sort' => 1,
                'class' => null,
                'menu' => 5,
                'depth' => 0,
                'is_custom_menu' => 0,
            ],
            [
                'label' => 'Transactions',
                'link' => 'transactions',
                'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\Vendor\\\\VendorTransactionController@index", "route_name":["vendorTransaction.index", "vendorTransaction.pdf", "vendorTransaction.csv"], "menu_lavel":"3"}',
                'is_default' => 1,
                'icon' => 'fas fa-exchange-alt',
                'parent' => 0,
                'sort' => 5,
                'class' => null,
                'menu' => 5,
                'depth' => 0,
                'is_custom_menu' => 0,
            ],
            [
                'label' => 'Refunds',
                'link' => 'refund-requests',
                'params' => '{"permission":"Modules\\\\Refund\\\\Http\\\\Controllers\\\\Vendor\\\\RefundController@index","route_name":["vendor.refund.index"], "menu_level":"5"}',
                'is_default' => 1,
                'icon' => 'fas fa-retweet',
                'parent' => 0,
                'sort' => 6,
                'class' => null,
                'menu' => 5,
                'depth' => 0,
                'is_custom_menu' => 0,
            ],
            [
                'label' => 'KYC',
                'link' => 'kyc',
                'params' => '{"permission":"Modules\\\\FormBuilder\\\\Http\\\\Controllers\\\\Vendor\\\\KycController@userKycForm", "route_name":["kyc.user.show"], "menu_level":"5"}',
                'is_default' => 1,
                'icon' => 'far fa-address-card',
                'parent' => 0,
                'sort' => 9,
                'class' => null,
                'menu' => 5,
                'depth' => 0,
                'is_custom_menu' => 0,
            ],
            [
                'label' => 'Tickets',
                'link' => 'ticket/list',
                'params' => '{"permission":"Modules\\\\Ticket\\\\Http\\\\Controllers\\\\Vendor\\\\TicketController@index", "route_name":["vendor.threadAdd", "vendor.threadReply", "vendor.threads"], "menu_level":"5"}',
                'is_default' => 1,
                'icon' => 'fas fa-ticket-alt',
                'parent' => 0,
                'sort' => 11,
                'class' => null,
                'menu' => 5,
                'depth' => 0,
                'is_custom_menu' => 0,
            ],
        ];

        foreach ($menuItems as $menu) {
            MenuItems::updateOrCreate(
                ['menu' => $menu['menu'], 'link' => $menu['link']], // match by name
                $menu // data to update or insert
            );
        }



        $menuItems = [
            [
                'label' => 'Dashboard',
                'link' => 'dashboard',
                'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\VendorController@index","route_name":["vendor-dashboard"],"menu_level":"5"}',
                'is_default' => 1,
                'icon' => 'fas fa-home',
                'parent' => 0,
                'sort' => 0,
                'class' => null,
                'menu' => 6,
                'depth' => 0,
                'is_custom_menu' => 0,
            ],
            [
                'label' => 'Orders',
                'link' => 'orders',
                'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\Vendor\\\\VendorOrderController@index", "route_name":["vendorOrder.index", "vendorOrder.view", "vendorOrder.pdf", "vendorOrder.csv"], "menu_level":"5"}',
                'is_default' => 1,
                'icon' => 'fas fa-shopping-bag',
                'parent' => 0,
                'sort' => 2,
                'class' => null,
                'menu' => 6,
                'depth' => 0,
                'is_custom_menu' => 0,
            ],
            [
                'label' => 'Products',
                'link' => 'products',
                'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\Vendor\\\\ProductController@index","route_name":["vendor.products","vendor.product.view","vendor.product.related","vendor.product.search","vendor.product.update","vendor.product.edit", "vendor.product.store", "vendor.product.create", "vendor.product.import", "vendor.itemCsv", "vendor.itemPdf", "vendor.itemDestroy", "vendor.items"]}',
                'is_default' => 1,
                'icon' => 'fas fa-cube',
                'parent' => 0,
                'sort' => 1,
                'class' => null,
                'menu' => 6,
                'depth' => 0,
                'is_custom_menu' => 0,
            ],
            [
                'label' => 'Transactions',
                'link' => 'transactions',
                'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\Vendor\\\\VendorTransactionController@index", "route_name":["vendorTransaction.index", "vendorTransaction.pdf", "vendorTransaction.csv"], "menu_lavel":"3"}',
                'is_default' => 1,
                'icon' => 'fas fa-exchange-alt',
                'parent' => 0,
                'sort' => 5,
                'class' => null,
                'menu' => 6,
                'depth' => 0,
                'is_custom_menu' => 0,
            ],
            [
                'label' => 'Refunds',
                'link' => 'refund-requests',
                'params' => '{"permission":"Modules\\\\Refund\\\\Http\\\\Controllers\\\\Vendor\\\\RefundController@index","route_name":["vendor.refund.index"], "menu_level":"5"}',
                'is_default' => 1,
                'icon' => 'fas fa-retweet',
                'parent' => 0,
                'sort' => 6,
                'class' => null,
                'menu' => 6,
                'depth' => 0,
                'is_custom_menu' => 0,
            ],
            [
                'label' => 'KYC',
                'link' => 'kyc',
                'params' => '{"permission":"Modules\\\\FormBuilder\\\\Http\\\\Controllers\\\\Vendor\\\\KycController@userKycForm", "route_name":["kyc.user.show"], "menu_level":"5"}',
                'is_default' => 1,
                'icon' => 'far fa-address-card',
                'parent' => 0,
                'sort' => 9,
                'class' => null,
                'menu' => 6,
                'depth' => 0,
                'is_custom_menu' => 0,
            ],
            [
                'label' => 'Tickets',
                'link' => 'ticket/list',
                'params' => '{"permission":"Modules\\\\Ticket\\\\Http\\\\Controllers\\\\Vendor\\\\TicketController@index", "route_name":["vendor.threadAdd", "vendor.threadReply", "vendor.threads"], "menu_level":"5"}',
                'is_default' => 1,
                'icon' => 'fas fa-ticket-alt',
                'parent' => 0,
                'sort' => 11,
                'class' => null,
                'menu' => 6,
                'depth' => 0,
                'is_custom_menu' => 0,
            ],
            [
                'label' => 'Customers',
                'link' => 'customer',
                'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\Vendor\\\\CustomerController@index", "route_name":["vendor.customer"], "menu_level":"6"}',
                'is_default' => 1,
                'icon' => 'fas fa-users',
                'parent' => 0,
                'sort' => 3,
                'class' => null,
                'menu' => 6,
                'depth' => 0,
                'is_custom_menu' => 0,
            ],
            [
                'label' => 'Reviews',
                'link' => 'reviews',
                'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\ReviewController@index","route_name":["vendor.reviewCsv","vendor.reviewPdf","vendor.reviewDestroy","vendor.reviewUpdate","vendor.reviewView", "vendor.reviewEdit", "vendor.reviews"]}',
                'is_default' => 1,
                'icon' => 'fas fa-star',
                'parent' => 0,
                'sort' => 8,
                'class' => null,
                'menu' => 6,
                'depth' => 0,
                'is_custom_menu' => 0,
            ],
        ];

        foreach ($menuItems as $menu) {
            MenuItems::updateOrCreate(
                ['menu' => $menu['menu'], 'link' => $menu['link']], // match by name
                $menu // data to update or insert
            );
        }



        $menuItems = [
            [
                'label' => 'Dashboard',
                'link' => 'dashboard',
                'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\VendorController@index","route_name":["vendor-dashboard"],"menu_level":"5"}',
                'is_default' => 1,
                'icon' => 'fas fa-home',
                'parent' => 0,
                'sort' => 0,
                'class' => null,
                'menu' => 7,
                'depth' => 0,
                'is_custom_menu' => 0,
            ],
            [
                'label' => 'Orders',
                'link' => 'orders',
                'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\Vendor\\\\VendorOrderController@index", "route_name":["vendorOrder.index", "vendorOrder.view", "vendorOrder.pdf", "vendorOrder.csv"], "menu_level":"5"}',
                'is_default' => 1,
                'icon' => 'fas fa-shopping-bag',
                'parent' => 0,
                'sort' => 2,
                'class' => null,
                'menu' => 7,
                'depth' => 0,
                'is_custom_menu' => 0,
            ],
            [
                'label' => 'Products',
                'link' => 'products',
                'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\Vendor\\\\ProductController@index","route_name":["vendor.products","vendor.product.view","vendor.product.related","vendor.product.search","vendor.product.update","vendor.product.edit", "vendor.product.store", "vendor.product.create", "vendor.product.import", "vendor.itemCsv", "vendor.itemPdf", "vendor.itemDestroy", "vendor.items"]}',
                'is_default' => 1,
                'icon' => 'fas fa-cube',
                'parent' => 0,
                'sort' => 1,
                'class' => null,
                'menu' => 7,
                'depth' => 0,
                'is_custom_menu' => 0,
            ],
            [
                'label' => 'Transactions',
                'link' => 'transactions',
                'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\Vendor\\\\VendorTransactionController@index", "route_name":["vendorTransaction.index", "vendorTransaction.pdf", "vendorTransaction.csv"], "menu_lavel":"3"}',
                'is_default' => 1,
                'icon' => 'fas fa-exchange-alt',
                'parent' => 0,
                'sort' => 5,
                'class' => null,
                'menu' => 7,
                'depth' => 0,
                'is_custom_menu' => 0,
            ],
            [
                'label' => 'Refunds',
                'link' => 'refund-requests',
                'params' => '{"permission":"Modules\\\\Refund\\\\Http\\\\Controllers\\\\Vendor\\\\RefundController@index","route_name":["vendor.refund.index"], "menu_level":"5"}',
                'is_default' => 1,
                'icon' => 'fas fa-retweet',
                'parent' => 0,
                'sort' => 6,
                'class' => null,
                'menu' => 7,
                'depth' => 0,
                'is_custom_menu' => 0,
            ],
            [
                'label' => 'KYC',
                'link' => 'kyc',
                'params' => '{"permission":"Modules\\\\FormBuilder\\\\Http\\\\Controllers\\\\Vendor\\\\KycController@userKycForm", "route_name":["kyc.user.show"], "menu_level":"5"}',
                'is_default' => 1,
                'icon' => 'far fa-address-card',
                'parent' => 0,
                'sort' => 9,
                'class' => null,
                'menu' => 7,
                'depth' => 0,
                'is_custom_menu' => 0,
            ],
            [
                'label' => 'Tickets',
                'link' => 'ticket/list',
                'params' => '{"permission":"Modules\\\\Ticket\\\\Http\\\\Controllers\\\\Vendor\\\\TicketController@index", "route_name":["vendor.threadAdd", "vendor.threadReply", "vendor.threads"], "menu_level":"5"}',
                'is_default' => 1,
                'icon' => 'fas fa-ticket-alt',
                'parent' => 0,
                'sort' => 11,
                'class' => null,
                'menu' => 7,
                'depth' => 0,
                'is_custom_menu' => 0,
            ],
            [
                'label' => 'Customers',
                'link' => 'customer',
                'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\Vendor\\\\CustomerController@index", "route_name":["vendor.customer"], "menu_level":"6"}',
                'is_default' => 1,
                'icon' => 'fas fa-users',
                'parent' => 0,
                'sort' => 3,
                'class' => null,
                'menu' => 7,
                'depth' => 0,
                'is_custom_menu' => 0,
            ],
            [
                'label' => 'Reviews',
                'link' => 'reviews',
                'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\ReviewController@index","route_name":["vendor.reviewCsv","vendor.reviewPdf","vendor.reviewDestroy","vendor.reviewUpdate","vendor.reviewView", "vendor.reviewEdit", "vendor.reviews"]}',
                'is_default' => 1,
                'icon' => 'fas fa-star',
                'parent' => 0,
                'sort' => 8,
                'class' => null,
                'menu' => 7,
                'depth' => 0,
                'is_custom_menu' => 0,
            ],
            ['label' => 'Coupons',
                'link' => 'coupons',
                'params' => '{"permission":"Modules\\\\Coupon\\\\Http\\\\Controllers\\\\Vendor\\\\CouponController@index","route_name":["vendor.coupons", "vendor.couponCreate", "vendor.couponEdit", "vendor.couponProduct"]}',
                'is_default' => 1,
                'icon' => 'fas fa-percent',
                'parent' => 0,
                'sort' => 4,
                'class' => null,
                'menu' => 7,
                'depth' => 0,
                'is_custom_menu' => 0,
            ],
            [
                'label' => 'Import Products',
                'link' => 'import/products',
                'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\Vendor\\\\ImportController@productImport", "route_name":["vendor.epz.import.products"], "menu_level":"3"}',
                'is_default' => 1,
                'icon' => 'fas fa-download',
                'parent' => 0,
                'sort' => 7,
                'class' => null,
                'menu' => 7,
                'depth' => 0,
                'is_custom_menu' => 0,
            ],
            [
                'label' => 'Export Products',
                'link' => 'export/products',
                'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\Vendor\\\\ExportController@productExport", "route_name":["vendor.epz.export.products"], "menu_level":"3"}',
                'is_default' => 1,
                'icon' => 'fas fa-download',
                'parent' => 0,
                'sort' => 6,
                'class' => null,
                'menu' => 7,
                'depth' => 1,
                'is_custom_menu' => 0,
            ],
            [
                'label' => 'Withdrawals',
                'link' => 'withdrawals',
                'params' => '{"permission":"App\\\\Http\\\\Controllers\\\\Vendor\\\\WithdrawalController@index","route_name":["vendorWithdrawal.index", "vendorWithdrawal.setting", "vendorWithdrawal.money"]}',
                'is_default' => 1,
                'icon' => 'far fa-credit-card',
                'parent' => 0,
                'sort' => 3,
                'class' => null,
                'menu' => 7,
                'depth' => 0,
                'is_custom_menu' => 0,
            ],
        ];

        foreach ($menuItems as $menu) {
            MenuItems::updateOrCreate(
                ['menu' => $menu['menu'], 'link' => $menu['link']], // match by name
                $menu // data to update or insert
            );
        }

    }
}
