<?php

namespace Modules\Dummy\Database\Seeders\Core;

use Illuminate\Database\Seeder;

class ObjectFilesTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::table('object_files')->delete();

        \DB::table('object_files')->insert([
            0 => [
                'id' => 2,
                'object_type' => 'theme_options',
                'object_id' => 1,
                'file_id' => 579,
            ],
            1 => [
                'id' => 3,
                'object_type' => 'theme_options',
                'object_id' => 4,
                'file_id' => 576,
            ],
            2 => [
                'id' => 4,
                'object_type' => 'theme_options',
                'object_id' => 2,
                'file_id' => 577,
            ],
            3 => [
                'id' => 5,
                'object_type' => 'theme_options',
                'object_id' => 3,
                'file_id' => 578,
            ],
            4 => [
                'id' => 6,
                'object_type' => 'theme_options',
                'object_id' => 11,
                'file_id' => 580,
            ],
            5 => [
                'id' => 8,
                'object_type' => 'users',
                'object_id' => 5,
                'file_id' => 678,
            ],
            6 => [
                'id' => 9,
                'object_type' => 'users',
                'object_id' => 8,
                'file_id' => 676,
            ],
            7 => [
                'id' => 10,
                'object_type' => 'users',
                'object_id' => 7,
                'file_id' => 677,
            ],
            8 => [
                'id' => 11,
                'object_type' => 'users',
                'object_id' => 9,
                'file_id' => 670,
            ],
            9 => [
                'id' => 12,
                'object_type' => 'users',
                'object_id' => 15,
                'file_id' => 670,
            ],
            10 => [
                'id' => 13,
                'object_type' => 'users',
                'object_id' => 16,
                'file_id' => 673,
            ],
            11 => [
                'id' => 14,
                'object_type' => 'users',
                'object_id' => 17,
                'file_id' => 674,
            ],
            12 => [
                'id' => 15,
                'object_type' => 'users',
                'object_id' => 18,
                'file_id' => 675,
            ],
            13 => [
                'id' => 16,
                'object_type' => 'users',
                'object_id' => 19,
                'file_id' => 680,
            ],
            14 => [
                'id' => 17,
                'object_type' => 'categories',
                'object_id' => 38,
                'file_id' => 595,
            ],
            15 => [
                'id' => 18,
                'object_type' => 'categories',
                'object_id' => 39,
                'file_id' => 596,
            ],
            16 => [
                'id' => 19,
                'object_type' => 'categories',
                'object_id' => 41,
                'file_id' => 597,
            ],
            17 => [
                'id' => 20,
                'object_type' => 'categories',
                'object_id' => 42,
                'file_id' => 599,
            ],
            18 => [
                'id' => 21,
                'object_type' => 'categories',
                'object_id' => 46,
                'file_id' => 598,
            ],
            19 => [
                'id' => 22,
                'object_type' => 'categories',
                'object_id' => 47,
                'file_id' => 600,
            ],
            20 => [
                'id' => 23,
                'object_type' => 'categories',
                'object_id' => 48,
                'file_id' => 601,
            ],
            21 => [
                'id' => 24,
                'object_type' => 'categories',
                'object_id' => 49,
                'file_id' => 602,
            ],
            22 => [
                'id' => 25,
                'object_type' => 'slides',
                'object_id' => 1,
                'file_id' => 1127,
            ],
            23 => [
                'id' => 26,
                'object_type' => 'slides',
                'object_id' => 2,
                'file_id' => 603,
            ],
            24 => [
                'id' => 27,
                'object_type' => 'slides',
                'object_id' => 3,
                'file_id' => 606,
            ],
            25 => [
                'id' => 28,
                'object_type' => 'slides',
                'object_id' => 4,
                'file_id' => 1112,
            ],
            26 => [
                'id' => 29,
                'object_type' => 'blogs',
                'object_id' => 19,
                'file_id' => 998,
            ],
            27 => [
                'id' => 30,
                'object_type' => 'blogs',
                'object_id' => 20,
                'file_id' => 999,
            ],
            28 => [
                'id' => 31,
                'object_type' => 'blogs',
                'object_id' => 21,
                'file_id' => 619,
            ],
            29 => [
                'id' => 32,
                'object_type' => 'blogs',
                'object_id' => 22,
                'file_id' => 1000,
            ],
            30 => [
                'id' => 33,
                'object_type' => 'blogs',
                'object_id' => 23,
                'file_id' => 1005,
            ],
            31 => [
                'id' => 34,
                'object_type' => 'blogs',
                'object_id' => 24,
                'file_id' => 1004,
            ],
            32 => [
                'id' => 35,
                'object_type' => 'blogs',
                'object_id' => 25,
                'file_id' => 1003,
            ],
            33 => [
                'id' => 36,
                'object_type' => 'blogs',
                'object_id' => 26,
                'file_id' => 1002,
            ],
            34 => [
                'id' => 37,
                'object_type' => 'blogs',
                'object_id' => 27,
                'file_id' => 1001,
            ],
            35 => [
                'id' => 38,
                'object_type' => 'theme_options',
                'object_id' => 15,
                'file_id' => 651,
            ],
            36 => [
                'id' => 39,
                'object_type' => 'theme_options',
                'object_id' => 16,
                'file_id' => 653,
            ],
            37 => [
                'id' => 40,
                'object_type' => 'theme_options',
                'object_id' => 17,
                'file_id' => 652,
            ],
            38 => [
                'id' => 42,
                'object_type' => 'users',
                'object_id' => 1,
                'file_id' => 667,
            ],
            39 => [
                'id' => 43,
                'object_type' => 'users',
                'object_id' => 2,
                'file_id' => 668,
            ],
            40 => [
                'id' => 44,
                'object_type' => 'users',
                'object_id' => 3,
                'file_id' => 669,
            ],
            41 => [
                'id' => 45,
                'object_type' => 'users',
                'object_id' => 6,
                'file_id' => 672,
            ],
            42 => [
                'id' => 46,
                'object_type' => 'users',
                'object_id' => 4,
                'file_id' => 679,
            ],
            43 => [
                'id' => 47,
                'object_type' => 'brands',
                'object_id' => 17,
                'file_id' => 681,
            ],
            44 => [
                'id' => 48,
                'object_type' => 'brands',
                'object_id' => 1,
                'file_id' => 682,
            ],
            45 => [
                'id' => 49,
                'object_type' => 'brands',
                'object_id' => 2,
                'file_id' => 683,
            ],
            46 => [
                'id' => 50,
                'object_type' => 'brands',
                'object_id' => 5,
                'file_id' => 684,
            ],
            47 => [
                'id' => 51,
                'object_type' => 'brands',
                'object_id' => 9,
                'file_id' => 686,
            ],
            48 => [
                'id' => 52,
                'object_type' => 'brands',
                'object_id' => 8,
                'file_id' => 687,
            ],
            49 => [
                'id' => 53,
                'object_type' => 'brands',
                'object_id' => 10,
                'file_id' => 688,
            ],
            50 => [
                'id' => 54,
                'object_type' => 'brands',
                'object_id' => 7,
                'file_id' => 689,
            ],
            51 => [
                'id' => 55,
                'object_type' => 'brands',
                'object_id' => 4,
                'file_id' => 690,
            ],
            52 => [
                'id' => 56,
                'object_type' => 'brands',
                'object_id' => 6,
                'file_id' => 691,
            ],
            53 => [
                'id' => 57,
                'object_type' => 'brands',
                'object_id' => 3,
                'file_id' => 692,
            ],
            54 => [
                'id' => 58,
                'object_type' => 'brands',
                'object_id' => 11,
                'file_id' => 693,
            ],
            55 => [
                'id' => 59,
                'object_type' => 'brands',
                'object_id' => 12,
                'file_id' => 694,
            ],
            56 => [
                'id' => 60,
                'object_type' => 'brands',
                'object_id' => 13,
                'file_id' => 695,
            ],
            57 => [
                'id' => 61,
                'object_type' => 'brands',
                'object_id' => 14,
                'file_id' => 696,
            ],
            58 => [
                'id' => 62,
                'object_type' => 'brands',
                'object_id' => 15,
                'file_id' => 697,
            ],
            59 => [
                'id' => 63,
                'object_type' => 'brands',
                'object_id' => 16,
                'file_id' => 698,
            ],
            60 => [
                'id' => 64,
                'object_type' => 'brands',
                'object_id' => 18,
                'file_id' => 699,
            ],
            61 => [
                'id' => 65,
                'object_type' => 'brands',
                'object_id' => 19,
                'file_id' => 700,
            ],
            62 => [
                'id' => 66,
                'object_type' => 'brands',
                'object_id' => 20,
                'file_id' => 701,
            ],
            63 => [
                'id' => 67,
                'object_type' => 'brands',
                'object_id' => 48,
                'file_id' => 702,
            ],
            64 => [
                'id' => 68,
                'object_type' => 'brands',
                'object_id' => 46,
                'file_id' => 703,
            ],
            65 => [
                'id' => 69,
                'object_type' => 'brands',
                'object_id' => 49,
                'file_id' => 704,
            ],
            66 => [
                'id' => 70,
                'object_type' => 'brands',
                'object_id' => 21,
                'file_id' => 705,
            ],
            67 => [
                'id' => 71,
                'object_type' => 'brands',
                'object_id' => 22,
                'file_id' => 706,
            ],
            68 => [
                'id' => 72,
                'object_type' => 'brands',
                'object_id' => 23,
                'file_id' => 707,
            ],
            69 => [
                'id' => 73,
                'object_type' => 'brands',
                'object_id' => 24,
                'file_id' => 708,
            ],
            70 => [
                'id' => 74,
                'object_type' => 'brands',
                'object_id' => 26,
                'file_id' => 709,
            ],
            71 => [
                'id' => 75,
                'object_type' => 'brands',
                'object_id' => 27,
                'file_id' => 710,
            ],
            72 => [
                'id' => 76,
                'object_type' => 'brands',
                'object_id' => 28,
                'file_id' => 711,
            ],
            73 => [
                'id' => 77,
                'object_type' => 'brands',
                'object_id' => 44,
                'file_id' => 712,
            ],
            74 => [
                'id' => 78,
                'object_type' => 'brands',
                'object_id' => 29,
                'file_id' => 713,
            ],
            75 => [
                'id' => 79,
                'object_type' => 'brands',
                'object_id' => 45,
                'file_id' => 714,
            ],
            76 => [
                'id' => 80,
                'object_type' => 'brands',
                'object_id' => 43,
                'file_id' => 715,
            ],
            77 => [
                'id' => 81,
                'object_type' => 'brands',
                'object_id' => 40,
                'file_id' => 716,
            ],
            78 => [
                'id' => 82,
                'object_type' => 'brands',
                'object_id' => 42,
                'file_id' => 717,
            ],
            79 => [
                'id' => 83,
                'object_type' => 'brands',
                'object_id' => 41,
                'file_id' => 718,
            ],
            80 => [
                'id' => 84,
                'object_type' => 'brands',
                'object_id' => 25,
                'file_id' => 719,
            ],
            81 => [
                'id' => 85,
                'object_type' => 'brands',
                'object_id' => 39,
                'file_id' => 720,
            ],
            82 => [
                'id' => 86,
                'object_type' => 'brands',
                'object_id' => 37,
                'file_id' => 721,
            ],
            83 => [
                'id' => 87,
                'object_type' => 'brands',
                'object_id' => 32,
                'file_id' => 722,
            ],
            84 => [
                'id' => 88,
                'object_type' => 'brands',
                'object_id' => 33,
                'file_id' => 723,
            ],
            85 => [
                'id' => 89,
                'object_type' => 'brands',
                'object_id' => 34,
                'file_id' => 724,
            ],
            86 => [
                'id' => 90,
                'object_type' => 'brands',
                'object_id' => 36,
                'file_id' => 725,
            ],
            87 => [
                'id' => 91,
                'object_type' => 'brands',
                'object_id' => 31,
                'file_id' => 726,
            ],
            88 => [
                'id' => 92,
                'object_type' => 'brands',
                'object_id' => 35,
                'file_id' => 727,
            ],
            89 => [
                'id' => 93,
                'object_type' => 'brands',
                'object_id' => 47,
                'file_id' => 728,
            ],
            90 => [
                'id' => 94,
                'object_type' => 'brands',
                'object_id' => 50,
                'file_id' => 729,
            ],
            91 => [
                'id' => 95,
                'object_type' => 'brands',
                'object_id' => 38,
                'file_id' => 730,
            ],
            92 => [
                'id' => 96,
                'object_type' => 'brands',
                'object_id' => 30,
                'file_id' => 731,
            ],
            93 => [
                'id' => 97,
                'object_type' => 'vendors_meta',
                'object_id' => 2,
                'file_id' => 733,
            ],
            94 => [
                'id' => 98,
                'object_type' => 'vendors_meta',
                'object_id' => 3,
                'file_id' => 732,
            ],
            95 => [
                'id' => 99,
                'object_type' => 'vendors_meta',
                'object_id' => 5,
                'file_id' => 734,
            ],
            96 => [
                'id' => 100,
                'object_type' => 'vendors_meta',
                'object_id' => 6,
                'file_id' => 735,
            ],
            97 => [
                'id' => 101,
                'object_type' => 'vendors_meta',
                'object_id' => 8,
                'file_id' => 739,
            ],
            98 => [
                'id' => 102,
                'object_type' => 'vendors_meta',
                'object_id' => 9,
                'file_id' => 738,
            ],
            99 => [
                'id' => 103,
                'object_type' => 'vendors_meta',
                'object_id' => 11,
                'file_id' => 741,
            ],
            100 => [
                'id' => 104,
                'object_type' => 'vendors_meta',
                'object_id' => 12,
                'file_id' => 740,
            ],
            101 => [
                'id' => 105,
                'object_type' => 'vendors_meta',
                'object_id' => 14,
                'file_id' => 743,
            ],
            102 => [
                'id' => 106,
                'object_type' => 'vendors_meta',
                'object_id' => 15,
                'file_id' => 742,
            ],
            103 => [
                'id' => 107,
                'object_type' => 'vendors_meta',
                'object_id' => 17,
                'file_id' => 745,
            ],
            104 => [
                'id' => 108,
                'object_type' => 'vendors_meta',
                'object_id' => 18,
                'file_id' => 744,
            ],
            105 => [
                'id' => 109,
                'object_type' => 'vendors_meta',
                'object_id' => 20,
                'file_id' => 747,
            ],
            106 => [
                'id' => 110,
                'object_type' => 'vendors_meta',
                'object_id' => 21,
                'file_id' => 746,
            ],
            107 => [
                'id' => 111,
                'object_type' => 'theme_options',
                'object_id' => 19,
                'file_id' => 797,
            ],
            108 => [
                'id' => 112,
                'object_type' => 'theme_options',
                'object_id' => 20,
                'file_id' => 577,
            ],
            109 => [
                'id' => 113,
                'object_type' => 'theme_options',
                'object_id' => 21,
                'file_id' => 578,
            ],
            110 => [
                'id' => 114,
                'object_type' => 'theme_options',
                'object_id' => 22,
                'file_id' => 576,
            ],
            111 => [
                'id' => 115,
                'object_type' => 'theme_options',
                'object_id' => 28,
                'file_id' => 796,
            ],
            112 => [
                'id' => 116,
                'object_type' => 'theme_options',
                'object_id' => 32,
                'file_id' => 651,
            ],
            113 => [
                'id' => 117,
                'object_type' => 'theme_options',
                'object_id' => 33,
                'file_id' => 653,
            ],
            114 => [
                'id' => 118,
                'object_type' => 'theme_options',
                'object_id' => 34,
                'file_id' => 652,
            ],
            115 => [
                'id' => 119,
                'object_type' => 'theme_options',
                'object_id' => 36,
                'file_id' => 799,
            ],
            116 => [
                'id' => 120,
                'object_type' => 'theme_options',
                'object_id' => 37,
                'file_id' => 577,
            ],
            117 => [
                'id' => 121,
                'object_type' => 'theme_options',
                'object_id' => 38,
                'file_id' => 578,
            ],
            118 => [
                'id' => 122,
                'object_type' => 'theme_options',
                'object_id' => 39,
                'file_id' => 576,
            ],
            119 => [
                'id' => 123,
                'object_type' => 'theme_options',
                'object_id' => 45,
                'file_id' => 798,
            ],
            120 => [
                'id' => 124,
                'object_type' => 'theme_options',
                'object_id' => 49,
                'file_id' => 651,
            ],
            121 => [
                'id' => 125,
                'object_type' => 'theme_options',
                'object_id' => 50,
                'file_id' => 653,
            ],
            122 => [
                'id' => 126,
                'object_type' => 'theme_options',
                'object_id' => 51,
                'file_id' => 652,
            ],
            123 => [
                'id' => 127,
                'object_type' => 'theme_options',
                'object_id' => 53,
                'file_id' => 795,
            ],
            124 => [
                'id' => 128,
                'object_type' => 'theme_options',
                'object_id' => 54,
                'file_id' => 577,
            ],
            125 => [
                'id' => 129,
                'object_type' => 'theme_options',
                'object_id' => 55,
                'file_id' => 578,
            ],
            126 => [
                'id' => 130,
                'object_type' => 'theme_options',
                'object_id' => 56,
                'file_id' => 576,
            ],
            127 => [
                'id' => 131,
                'object_type' => 'theme_options',
                'object_id' => 62,
                'file_id' => 794,
            ],
            128 => [
                'id' => 132,
                'object_type' => 'theme_options',
                'object_id' => 66,
                'file_id' => 651,
            ],
            129 => [
                'id' => 133,
                'object_type' => 'theme_options',
                'object_id' => 67,
                'file_id' => 653,
            ],
            130 => [
                'id' => 134,
                'object_type' => 'theme_options',
                'object_id' => 68,
                'file_id' => 652,
            ],
            131 => [
                'id' => 135,
                'object_type' => 'slides',
                'object_id' => 5,
                'file_id' => 768,
            ],
            132 => [
                'id' => 136,
                'object_type' => 'slides',
                'object_id' => 6,
                'file_id' => 769,
            ],
            133 => [
                'id' => 137,
                'object_type' => 'slides',
                'object_id' => 7,
                'file_id' => 770,
            ],
            134 => [
                'id' => 138,
                'object_type' => 'slides',
                'object_id' => 8,
                'file_id' => 771,
            ],
            135 => [
                'id' => 139,
                'object_type' => 'slides',
                'object_id' => 9,
                'file_id' => 772,
            ],
            136 => [
                'id' => 140,
                'object_type' => 'slides',
                'object_id' => 10,
                'file_id' => 773,
            ],
            137 => [
                'id' => 141,
                'object_type' => 'slides',
                'object_id' => 11,
                'file_id' => 774,
            ],
            138 => [
                'id' => 142,
                'object_type' => 'slides',
                'object_id' => 12,
                'file_id' => 775,
            ],
            139 => [
                'id' => 143,
                'object_type' => 'slides',
                'object_id' => 13,
                'file_id' => 776,
            ],
            140 => [
                'id' => 144,
                'object_type' => 'slides',
                'object_id' => 15,
                'file_id' => 777,
            ],
            141 => [
                'id' => 145,
                'object_type' => 'slides',
                'object_id' => 16,
                'file_id' => 778,
            ],
            142 => [
                'id' => 146,
                'object_type' => 'slides',
                'object_id' => 17,
                'file_id' => 779,
            ],
            143 => [
                'id' => 147,
                'object_type' => 'slides',
                'object_id' => 18,
                'file_id' => 780,
            ],
            144 => [
                'id' => 148,
                'object_type' => 'slides',
                'object_id' => 19,
                'file_id' => 781,
            ],
            145 => [
                'id' => 149,
                'object_type' => 'slides',
                'object_id' => 20,
                'file_id' => 782,
            ],
            146 => [
                'id' => 150,
                'object_type' => 'slides',
                'object_id' => 21,
                'file_id' => 783,
            ],
            147 => [
                'id' => 151,
                'object_type' => 'slides',
                'object_id' => 22,
                'file_id' => 784,
            ],
            148 => [
                'id' => 152,
                'object_type' => 'slides',
                'object_id' => 23,
                'file_id' => 785,
            ],
            149 => [
                'id' => 153,
                'object_type' => 'slides',
                'object_id' => 24,
                'file_id' => 786,
            ],
            150 => [
                'id' => 154,
                'object_type' => 'preferences',
                'object_id' => 48,
                'file_id' => 792,
            ],
            151 => [
                'id' => 155,
                'object_type' => 'preferences',
                'object_id' => 47,
                'file_id' => 793,
            ],
            152 => [
                'id' => 156,
                'object_type' => 'users',
                'object_id' => 20,
                'file_id' => 1062,
            ],
            153 => [
                'id' => 157,
                'object_type' => 'users',
                'object_id' => 21,
                'file_id' => 1063,
            ],
            154 => [
                'id' => 158,
                'object_type' => 'vendors_meta',
                'object_id' => 24,
                'file_id' => 801,
            ],
            155 => [
                'id' => 159,
                'object_type' => 'theme_options',
                'object_id' => 70,
                'file_id' => 987,
            ],
            156 => [
                'id' => 160,
                'object_type' => 'theme_options',
                'object_id' => 71,
                'file_id' => 577,
            ],
            157 => [
                'id' => 161,
                'object_type' => 'theme_options',
                'object_id' => 72,
                'file_id' => 578,
            ],
            158 => [
                'id' => 162,
                'object_type' => 'theme_options',
                'object_id' => 73,
                'file_id' => 576,
            ],
            159 => [
                'id' => 163,
                'object_type' => 'theme_options',
                'object_id' => 79,
                'file_id' => 986,
            ],
            160 => [
                'id' => 164,
                'object_type' => 'theme_options',
                'object_id' => 83,
                'file_id' => 651,
            ],
            161 => [
                'id' => 165,
                'object_type' => 'theme_options',
                'object_id' => 84,
                'file_id' => 653,
            ],
            162 => [
                'id' => 166,
                'object_type' => 'theme_options',
                'object_id' => 85,
                'file_id' => 652,
            ],
            163 => [
                'id' => 167,
                'object_type' => 'slides',
                'object_id' => 25,
                'file_id' => 993,
            ],
            164 => [
                'id' => 168,
                'object_type' => 'slides',
                'object_id' => 26,
                'file_id' => 994,
            ],
            165 => [
                'id' => 169,
                'object_type' => 'slides',
                'object_id' => 27,
                'file_id' => 995,
            ],
            166 => [
                'id' => 170,
                'object_type' => 'slides',
                'object_id' => 28,
                'file_id' => 996,
            ],
            167 => [
                'id' => 171,
                'object_type' => 'slides',
                'object_id' => 29,
                'file_id' => 997,
            ],
            168 => [
                'id' => 172,
                'object_type' => 'slides',
                'object_id' => 30,
                'file_id' => 1023,
            ],
            169 => [
                'id' => 173,
                'object_type' => 'slides',
                'object_id' => 31,
                'file_id' => 1024,
            ],
            170 => [
                'id' => 174,
                'object_type' => 'slides',
                'object_id' => 32,
                'file_id' => 1025,
            ],
            171 => [
                'id' => 175,
                'object_type' => 'theme_options',
                'object_id' => 92,
                'file_id' => 579,
            ],
            172 => [
                'id' => 179,
                'object_type' => 'theme_options',
                'object_id' => 101,
                'file_id' => 580,
            ],
            173 => [
                'id' => 180,
                'object_type' => 'theme_options',
                'object_id' => 105,
                'file_id' => 651,
            ],
            174 => [
                'id' => 181,
                'object_type' => 'theme_options',
                'object_id' => 106,
                'file_id' => 653,
            ],
            175 => [
                'id' => 182,
                'object_type' => 'theme_options',
                'object_id' => 107,
                'file_id' => 652,
            ],
            176 => [
                'id' => 183,
                'object_type' => 'slides',
                'object_id' => 33,
                'file_id' => 1026,
            ],
            177 => [
                'id' => 184,
                'object_type' => 'slides',
                'object_id' => 34,
                'file_id' => 1027,
            ],
            178 => [
                'id' => 185,
                'object_type' => 'slides',
                'object_id' => 35,
                'file_id' => 1028,
            ],
            179 => [
                'id' => 186,
                'object_type' => 'slides',
                'object_id' => 36,
                'file_id' => 1029,
            ],
            180 => [
                'id' => 187,
                'object_type' => 'slides',
                'object_id' => 37,
                'file_id' => 1030,
            ],
            181 => [
                'id' => 188,
                'object_type' => 'theme_options',
                'object_id' => 110,
                'file_id' => 1032,
            ],
            182 => [
                'id' => 191,
                'object_type' => 'theme_options',
                'object_id' => 113,
                'file_id' => 576,
            ],
            183 => [
                'id' => 192,
                'object_type' => 'theme_options',
                'object_id' => 119,
                'file_id' => 1031,
            ],
            184 => [
                'id' => 193,
                'object_type' => 'theme_options',
                'object_id' => 123,
                'file_id' => 651,
            ],
            185 => [
                'id' => 194,
                'object_type' => 'theme_options',
                'object_id' => 124,
                'file_id' => 653,
            ],
            186 => [
                'id' => 195,
                'object_type' => 'theme_options',
                'object_id' => 125,
                'file_id' => 652,
            ],
            187 => [
                'id' => 196,
                'object_type' => 'slides',
                'object_id' => 38,
                'file_id' => 1033,
            ],
            188 => [
                'id' => 197,
                'object_type' => 'slides',
                'object_id' => 39,
                'file_id' => 1034,
            ],
            189 => [
                'id' => 198,
                'object_type' => 'slides',
                'object_id' => 40,
                'file_id' => 1035,
            ],
            190 => [
                'id' => 199,
                'object_type' => 'slides',
                'object_id' => 41,
                'file_id' => 1036,
            ],
            191 => [
                'id' => 200,
                'object_type' => 'slides',
                'object_id' => 42,
                'file_id' => 1037,
            ],
            192 => [
                'id' => 201,
                'object_type' => 'theme_options',
                'object_id' => 129,
                'file_id' => 1032,
            ],
            193 => [
                'id' => 204,
                'object_type' => 'theme_options',
                'object_id' => 132,
                'file_id' => 576,
            ],
            194 => [
                'id' => 205,
                'object_type' => 'theme_options',
                'object_id' => 138,
                'file_id' => 580,
            ],
            195 => [
                'id' => 206,
                'object_type' => 'theme_options',
                'object_id' => 142,
                'file_id' => 651,
            ],
            196 => [
                'id' => 207,
                'object_type' => 'theme_options',
                'object_id' => 143,
                'file_id' => 653,
            ],
            197 => [
                'id' => 208,
                'object_type' => 'theme_options',
                'object_id' => 144,
                'file_id' => 652,
            ],
            198 => [
                'id' => 209,
                'object_type' => 'slides',
                'object_id' => 43,
                'file_id' => 1068,
            ],
            199 => [
                'id' => 210,
                'object_type' => 'slides',
                'object_id' => 44,
                'file_id' => 1069,
            ],
            200 => [
                'id' => 211,
                'object_type' => 'slides',
                'object_id' => 45,
                'file_id' => 1070,
            ],
            201 => [
                'id' => 212,
                'object_type' => 'theme_options',
                'object_id' => 147,
                'file_id' => 1071,
            ],
            202 => [
                'id' => 216,
                'object_type' => 'theme_options',
                'object_id' => 156,
                'file_id' => 1071,
            ],
            203 => [
                'id' => 217,
                'object_type' => 'theme_options',
                'object_id' => 160,
                'file_id' => 651,
            ],
            204 => [
                'id' => 218,
                'object_type' => 'theme_options',
                'object_id' => 161,
                'file_id' => 653,
            ],
            205 => [
                'id' => 219,
                'object_type' => 'theme_options',
                'object_id' => 162,
                'file_id' => 652,
            ],
            206 => [
                'id' => 220,
                'object_type' => 'slides',
                'object_id' => 46,
                'file_id' => 1072,
            ],
            208 => [
                'id' => 223,
                'object_type' => 'categories',
                'object_id' => 526,
                'file_id' => 1075,
            ],
            209 => [
                'id' => 224,
                'object_type' => 'categories',
                'object_id' => 527,
                'file_id' => 1076,
            ],
            210 => [
                'id' => 225,
                'object_type' => 'categories',
                'object_id' => 528,
                'file_id' => 1077,
            ],
            211 => [
                'id' => 226,
                'object_type' => 'categories',
                'object_id' => 529,
                'file_id' => 1078,
            ],
            212 => [
                'id' => 227,
                'object_type' => 'categories',
                'object_id' => 530,
                'file_id' => 1079,
            ],
            213 => [
                'id' => 228,
                'object_type' => 'categories',
                'object_id' => 531,
                'file_id' => 1080,
            ],
            214 => [
                'id' => 229,
                'object_type' => 'categories',
                'object_id' => 532,
                'file_id' => 1081,
            ],
            215 => [
                'id' => 230,
                'object_type' => 'categories',
                'object_id' => 533,
                'file_id' => 1082,
            ],
            216 => [
                'id' => 231,
                'object_type' => 'categories',
                'object_id' => 525,
                'file_id' => 1083,
            ],
            217 => [
                'id' => 232,
                'object_type' => 'blogs',
                'object_id' => 28,
                'file_id' => 1100,
            ],
            218 => [
                'id' => 233,
                'object_type' => 'blogs',
                'object_id' => 29,
                'file_id' => 1101,
            ],
            219 => [
                'id' => 234,
                'object_type' => 'blogs',
                'object_id' => 30,
                'file_id' => 1102,
            ],
            220 => [
                'id' => 235,
                'object_type' => 'blogs',
                'object_id' => 31,
                'file_id' => 1113,
            ],
            221 => [
                'id' => 236,
                'object_type' => 'blogs',
                'object_id' => 32,
                'file_id' => 1114,
            ],
            222 => [
                'id' => 237,
                'object_type' => 'blogs',
                'object_id' => 33,
                'file_id' => 1115,
            ],
            223 => [
                'id' => 238,
                'object_type' => 'refunds',
                'object_id' => 1,
                'file_id' => 1128,
            ],
            224 => [
                'id' => 239,
                'object_type' => 'refunds',
                'object_id' => 2,
                'file_id' => 1129,
            ],
            225 => [
                'id' => 240,
                'object_type' => 'pages',
                'object_id' => 5,
                'file_id' => 1130,
            ],
            226 => [
                'id' => 241,
                'object_type' => 'users',
                'object_id' => 25,
                'file_id' => 1131,
            ],
            227 => [
                'id' => 242,
                'object_type' => 'vendors_meta',
                'object_id' => 26,
                'file_id' => 1133,
            ],
            228 => [
                'id' => 243,
                'object_type' => 'vendors_meta',
                'object_id' => 27,
                'file_id' => 1132,
            ],
            229 => [
                'id' => 244,
                'object_type' => 'users',
                'object_id' => 24,
                'file_id' => 1134,
            ],
            230 => [
                'id' => 245,
                'object_type' => 'vendors_meta',
                'object_id' => 29,
                'file_id' => 1136,
            ],
            231 => [
                'id' => 246,
                'object_type' => 'vendors_meta',
                'object_id' => 30,
                'file_id' => 1135,
            ],
            232 => [
                'id' => 247,
                'object_type' => 'users',
                'object_id' => 23,
                'file_id' => 1137,
            ],
            233 => [
                'id' => 248,
                'object_type' => 'vendors_meta',
                'object_id' => 32,
                'file_id' => 1139,
            ],
            234 => [
                'id' => 249,
                'object_type' => 'vendors_meta',
                'object_id' => 33,
                'file_id' => 1138,
            ],
            235 => [
                'id' => 250,
                'object_type' => 'users',
                'object_id' => 22,
                'file_id' => 1142,
            ],
            236 => [
                'id' => 251,
                'object_type' => 'vendors_meta',
                'object_id' => 35,
                'file_id' => 1141,
            ],
            237 => [
                'id' => 252,
                'object_type' => 'vendors_meta',
                'object_id' => 36,
                'file_id' => 1140,
            ],

        ]);

    }
}
