<?php

namespace Modules\Dummy\Database\Seeders\Core;

use Illuminate\Database\Seeder;

class OrderStatusHistoriesTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::table('order_status_histories')->delete();

        \DB::table('order_status_histories')->insert([
            0 => [
                'id' => 1,
                'product_id' => null,
                'order_id' => 1,
                'user_id' => null,
                'order_status_id' => 1,
                'note' => null,
            ],
            1 => [
                'id' => 2,
                'product_id' => 1205,
                'order_id' => 1,
                'user_id' => 1,
                'order_status_id' => 4,
                'note' => null,
            ],
            2 => [
                'id' => 3,
                'product_id' => 1203,
                'order_id' => 1,
                'user_id' => 15,
                'order_status_id' => 4,
                'note' => null,
            ],
            3 => [
                'id' => 4,
                'product_id' => 1204,
                'order_id' => 1,
                'user_id' => 15,
                'order_status_id' => 4,
                'note' => null,
            ],
            4 => [
                'id' => 5,
                'product_id' => null,
                'order_id' => 1,
                'user_id' => null,
                'order_status_id' => 4,
                'note' => 'System Generated',
            ],
            5 => [
                'id' => 6,
                'product_id' => null,
                'order_id' => 2,
                'user_id' => null,
                'order_status_id' => 1,
                'note' => null,
            ],
            6 => [
                'id' => 7,
                'product_id' => 1199,
                'order_id' => 2,
                'user_id' => 18,
                'order_status_id' => 4,
                'note' => null,
            ],
            7 => [
                'id' => 8,
                'product_id' => null,
                'order_id' => 2,
                'user_id' => null,
                'order_status_id' => 4,
                'note' => 'System Generated',
            ],
            8 => [
                'id' => 9,
                'product_id' => null,
                'order_id' => 3,
                'user_id' => null,
                'order_status_id' => 1,
                'note' => null,
            ],
            9 => [
                'id' => 10,
                'product_id' => null,
                'order_id' => 4,
                'user_id' => null,
                'order_status_id' => 1,
                'note' => null,
            ],
            10 => [
                'id' => 11,
                'product_id' => null,
                'order_id' => 5,
                'user_id' => null,
                'order_status_id' => 1,
                'note' => null,
            ],
            11 => [
                'id' => 12,
                'product_id' => 1275,
                'order_id' => 5,
                'user_id' => 1,
                'order_status_id' => 5,
                'note' => null,
            ],
            12 => [
                'id' => 13,
                'product_id' => 1275,
                'order_id' => 5,
                'user_id' => 1,
                'order_status_id' => 5,
                'note' => null,
            ],
            13 => [
                'id' => 14,
                'product_id' => null,
                'order_id' => 6,
                'user_id' => null,
                'order_status_id' => 1,
                'note' => null,
            ],
            14 => [
                'id' => 15,
                'product_id' => null,
                'order_id' => 7,
                'user_id' => null,
                'order_status_id' => 1,
                'note' => null,
            ],
            15 => [
                'id' => 16,
                'product_id' => 1151,
                'order_id' => 7,
                'user_id' => 18,
                'order_status_id' => 4,
                'note' => null,
            ],
            16 => [
                'id' => 17,
                'product_id' => 1200,
                'order_id' => 7,
                'user_id' => 15,
                'order_status_id' => 4,
                'note' => null,
            ],
            17 => [
                'id' => 18,
                'product_id' => 1183,
                'order_id' => 7,
                'user_id' => 1,
                'order_status_id' => 4,
                'note' => null,
            ],
            18 => [
                'id' => 19,
                'product_id' => null,
                'order_id' => 7,
                'user_id' => null,
                'order_status_id' => 4,
                'note' => 'System Generated',
            ],
            19 => [
                'id' => 20,
                'product_id' => null,
                'order_id' => 8,
                'user_id' => null,
                'order_status_id' => 1,
                'note' => null,
            ],
            20 => [
                'id' => 21,
                'product_id' => 1244,
                'order_id' => 8,
                'user_id' => 1,
                'order_status_id' => 6,
                'note' => null,
            ],
            21 => [
                'id' => 22,
                'product_id' => 1137,
                'order_id' => 8,
                'user_id' => 1,
                'order_status_id' => 6,
                'note' => null,
            ],
            22 => [
                'id' => 23,
                'product_id' => 1244,
                'order_id' => 8,
                'user_id' => 1,
                'order_status_id' => 6,
                'note' => null,
            ],
            23 => [
                'id' => 24,
                'product_id' => 1137,
                'order_id' => 8,
                'user_id' => 1,
                'order_status_id' => 6,
                'note' => null,
            ],
            24 => [
                'id' => 25,
                'product_id' => null,
                'order_id' => 9,
                'user_id' => null,
                'order_status_id' => 1,
                'note' => null,
            ],
            25 => [
                'id' => 26,
                'product_id' => null,
                'order_id' => 10,
                'user_id' => null,
                'order_status_id' => 1,
                'note' => null,
            ],
            26 => [
                'id' => 27,
                'product_id' => 1183,
                'order_id' => 10,
                'user_id' => 1,
                'order_status_id' => 4,
                'note' => null,
            ],
            27 => [
                'id' => 28,
                'product_id' => 1176,
                'order_id' => 10,
                'user_id' => 1,
                'order_status_id' => 4,
                'note' => null,
            ],
            28 => [
                'id' => 29,
                'product_id' => 1202,
                'order_id' => 10,
                'user_id' => 1,
                'order_status_id' => 4,
                'note' => null,
            ],
            29 => [
                'id' => 30,
                'product_id' => null,
                'order_id' => 10,
                'user_id' => null,
                'order_status_id' => 4,
                'note' => 'System Generated',
            ],
            30 => [
                'id' => 31,
                'product_id' => null,
                'order_id' => 11,
                'user_id' => null,
                'order_status_id' => 1,
                'note' => null,
            ],
            31 => [
                'id' => 32,
                'product_id' => null,
                'order_id' => 12,
                'user_id' => null,
                'order_status_id' => 1,
                'note' => null,
            ],
            32 => [
                'id' => 33,
                'product_id' => null,
                'order_id' => 13,
                'user_id' => null,
                'order_status_id' => 1,
                'note' => null,
            ],
            33 => [
                'id' => 34,
                'product_id' => null,
                'order_id' => 14,
                'user_id' => null,
                'order_status_id' => 1,
                'note' => null,
            ],
            34 => [
                'id' => 35,
                'product_id' => 1200,
                'order_id' => 11,
                'user_id' => 1,
                'order_status_id' => 4,
                'note' => null,
            ],
            35 => [
                'id' => 36,
                'product_id' => 1177,
                'order_id' => 11,
                'user_id' => 1,
                'order_status_id' => 4,
                'note' => null,
            ],
            36 => [
                'id' => 37,
                'product_id' => 1157,
                'order_id' => 11,
                'user_id' => 1,
                'order_status_id' => 4,
                'note' => null,
            ],
            37 => [
                'id' => 38,
                'product_id' => 1183,
                'order_id' => 12,
                'user_id' => 1,
                'order_status_id' => 4,
                'note' => null,
            ],
            38 => [
                'id' => 39,
                'product_id' => 1313,
                'order_id' => 12,
                'user_id' => 1,
                'order_status_id' => 4,
                'note' => null,
            ],
            39 => [
                'id' => 40,
                'product_id' => 1308,
                'order_id' => 12,
                'user_id' => 1,
                'order_status_id' => 4,
                'note' => null,
            ],
            40 => [
                'id' => 41,
                'product_id' => 1305,
                'order_id' => 12,
                'user_id' => 1,
                'order_status_id' => 4,
                'note' => null,
            ],
            41 => [
                'id' => 42,
                'product_id' => 1151,
                'order_id' => 12,
                'user_id' => 1,
                'order_status_id' => 4,
                'note' => null,
            ],
            42 => [
                'id' => 43,
                'product_id' => 1137,
                'order_id' => 13,
                'user_id' => 1,
                'order_status_id' => 4,
                'note' => null,
            ],
        ]);

    }
}
