<?php

namespace Modules\Dummy\Database\Seeders\Core;

use Illuminate\Database\Seeder;

class OrderCommissionsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::table('order_commissions')->delete();

        \DB::table('order_commissions')->insert([
            0 => [
                'id' => 1,
                'order_details_id' => 1,
                'vendor_id' => 16,
                'category_id' => 504,
                'amount' => '3.00000000',
                'approval_time' => randomDateBefore(1),
                'status' => 'Approve',
            ],
            1 => [
                'id' => 2,
                'order_details_id' => 2,
                'vendor_id' => 16,
                'category_id' => 504,
                'amount' => '3.00000000',
                'approval_time' => randomDateBefore(1),
                'status' => 'Approve',
            ],
            2 => [
                'id' => 3,
                'order_details_id' => 3,
                'vendor_id' => 16,
                'category_id' => 504,
                'amount' => '3.00000000',
                'approval_time' => randomDateBefore(1),
                'status' => 'Approve',
            ],
            3 => [
                'id' => 4,
                'order_details_id' => 4,
                'vendor_id' => 19,
                'category_id' => 518,
                'amount' => '3.00000000',
                'approval_time' => randomDateBefore(1),
                'status' => 'Approve',
            ],
            4 => [
                'id' => 5,
                'order_details_id' => 5,
                'vendor_id' => 1,
                'category_id' => null,
                'amount' => '3.00000000',
                'approval_time' => null,
                'status' => 'Pending',
            ],
            5 => [
                'id' => 6,
                'order_details_id' => 6,
                'vendor_id' => 19,
                'category_id' => null,
                'amount' => '3.00000000',
                'approval_time' => null,
                'status' => 'Pending',
            ],
            6 => [
                'id' => 7,
                'order_details_id' => 7,
                'vendor_id' => 19,
                'category_id' => null,
                'amount' => '3.00000000',
                'approval_time' => null,
                'status' => 'Pending',
            ],
            7 => [
                'id' => 8,
                'order_details_id' => 8,
                'vendor_id' => 16,
                'category_id' => 504,
                'amount' => '3.00000000',
                'approval_time' => null,
                'status' => 'Pending',
            ],
            8 => [
                'id' => 9,
                'order_details_id' => 9,
                'vendor_id' => 1,
                'category_id' => 39,
                'amount' => '3.00000000',
                'approval_time' => randomDateBefore(1),
                'status' => 'Approve',
            ],
            9 => [
                'id' => 10,
                'order_details_id' => 10,
                'vendor_id' => 16,
                'category_id' => 504,
                'amount' => '3.00000000',
                'approval_time' => randomDateBefore(1),
                'status' => 'Approve',
            ],
            10 => [
                'id' => 11,
                'order_details_id' => 11,
                'vendor_id' => 19,
                'category_id' => 512,
                'amount' => '3.00000000',
                'approval_time' => randomDateBefore(1),
                'status' => 'Approve',
            ],
            11 => [
                'id' => 12,
                'order_details_id' => 12,
                'vendor_id' => 1,
                'category_id' => null,
                'amount' => '3.00000000',
                'approval_time' => null,
                'status' => 'Pending',
            ],
            12 => [
                'id' => 13,
                'order_details_id' => 13,
                'vendor_id' => 2,
                'category_id' => 526,
                'amount' => '3.00000000',
                'approval_time' => null,
                'status' => 'Pending',
            ],
            13 => [
                'id' => 14,
                'order_details_id' => 14,
                'vendor_id' => 19,
                'category_id' => null,
                'amount' => '3.00000000',
                'approval_time' => null,
                'status' => 'Pending',
            ],
            14 => [
                'id' => 15,
                'order_details_id' => 15,
                'vendor_id' => 19,
                'category_id' => null,
                'amount' => '3.00000000',
                'approval_time' => null,
                'status' => 'Pending',
            ],
            15 => [
                'id' => 16,
                'order_details_id' => 16,
                'vendor_id' => 1,
                'category_id' => null,
                'amount' => '3.00000000',
                'approval_time' => null,
                'status' => 'Pending',
            ],
            16 => [
                'id' => 17,
                'order_details_id' => 17,
                'vendor_id' => 17,
                'category_id' => null,
                'amount' => '3.00000000',
                'approval_time' => null,
                'status' => 'Pending',
            ],
            17 => [
                'id' => 18,
                'order_details_id' => 18,
                'vendor_id' => 1,
                'category_id' => 39,
                'amount' => '3.00000000',
                'approval_time' => randomDateBefore(1),
                'status' => 'Approve',
            ],
            18 => [
                'id' => 19,
                'order_details_id' => 19,
                'vendor_id' => 1,
                'category_id' => 39,
                'amount' => '3.00000000',
                'approval_time' => randomDateBefore(1),
                'status' => 'Approve',
            ],
            19 => [
                'id' => 20,
                'order_details_id' => 20,
                'vendor_id' => 16,
                'category_id' => 504,
                'amount' => '3.00000000',
                'approval_time' => randomDateBefore(1),
                'status' => 'Approve',
            ],
            20 => [
                'id' => 21,
                'order_details_id' => 21,
                'vendor_id' => 16,
                'category_id' => 504,
                'amount' => '3.00000000',
                'approval_time' => randomDateBefore(1),
                'status' => 'Approve',
            ],
            21 => [
                'id' => 22,
                'order_details_id' => 22,
                'vendor_id' => 1,
                'category_id' => 39,
                'amount' => '3.00000000',
                'approval_time' => randomDateBefore(1),
                'status' => 'Approve',
            ],
            22 => [
                'id' => 23,
                'order_details_id' => 23,
                'vendor_id' => 1,
                'category_id' => 39,
                'amount' => '3.00000000',
                'approval_time' => randomDateBefore(1),
                'status' => 'Approve',
            ],
            23 => [
                'id' => 24,
                'order_details_id' => 24,
                'vendor_id' => 1,
                'category_id' => 39,
                'amount' => '3.00000000',
                'approval_time' => randomDateBefore(1),
                'status' => 'Approve',
            ],
            24 => [
                'id' => 25,
                'order_details_id' => 25,
                'vendor_id' => 19,
                'category_id' => null,
                'amount' => '3.00000000',
                'approval_time' => randomDateBefore(1),
                'status' => 'Approve',
            ],
            25 => [
                'id' => 26,
                'order_details_id' => 26,
                'vendor_id' => 19,
                'category_id' => null,
                'amount' => '3.00000000',
                'approval_time' => randomDateBefore(1),
                'status' => 'Approve',
            ],
            26 => [
                'id' => 27,
                'order_details_id' => 27,
                'vendor_id' => 19,
                'category_id' => null,
                'amount' => '3.00000000',
                'approval_time' => randomDateBefore(1),
                'status' => 'Approve',
            ],
            27 => [
                'id' => 28,
                'order_details_id' => 28,
                'vendor_id' => 19,
                'category_id' => 512,
                'amount' => '3.00000000',
                'approval_time' => randomDateBefore(1),
                'status' => 'Approve',
            ],
            28 => [
                'id' => 29,
                'order_details_id' => 29,
                'vendor_id' => 2,
                'category_id' => 526,
                'amount' => '3.00000000',
                'approval_time' => randomDateBefore(1),
                'status' => 'Approve',
            ],
            29 => [
                'id' => 30,
                'order_details_id' => 30,
                'vendor_id' => 1,
                'category_id' => 56,
                'amount' => '3.00000000',
                'approval_time' => null,
                'status' => 'Pending',
            ],
            30 => [
                'id' => 31,
                'order_details_id' => 31,
                'vendor_id' => 1,
                'category_id' => null,
                'amount' => '3.00000000',
                'approval_time' => null,
                'status' => 'Pending',
            ],
            31 => [
                'id' => 32,
                'order_details_id' => 32,
                'vendor_id' => 1,
                'category_id' => null,
                'amount' => '3.00000000',
                'approval_time' => null,
                'status' => 'Pending',
            ],
        ]);

    }
}
