<?php

namespace Modules\Dummy\Database\Seeders\Core;

use Illuminate\Database\Seeder;

class TagsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::table('tags')->delete();

        \DB::table('tags')->insert([
            0 => [
                'id' => 1,
                'name' => 'Samsung',
                'vendor_id' => 1,
                'product_counts' => 2,
                'status' => 'Active',
            ],
            1 => [
                'id' => 2,
                'name' => 'Tab',
                'vendor_id' => 1,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            2 => [
                'id' => 3,
                'name' => 'Galaxy',
                'vendor_id' => 1,
                'product_counts' => 2,
                'status' => 'Active',
            ],
            3 => [
                'id' => 4,
                'name' => 'Samsung Galaxy Tab',
                'vendor_id' => 1,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            4 => [
                'id' => 5,
                'name' => 'Smart Phone',
                'vendor_id' => 1,
                'product_counts' => 4,
                'status' => 'Active',
            ],
            5 => [
                'id' => 6,
                'name' => 'iPhone',
                'vendor_id' => 1,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            6 => [
                'id' => 7,
                'name' => ' 13 Pro',
                'vendor_id' => 1,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            7 => [
                'id' => 8,
                'name' => ' iPhone 13 Pro',
                'vendor_id' => 1,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            8 => [
                'id' => 9,
                'name' => 'A30',
                'vendor_id' => 1,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            9 => [
                'id' => 10,
                'name' => 'Nokia',
                'vendor_id' => 1,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            10 => [
                'id' => 11,
                'name' => 'Nokia 3.4 DS',
                'vendor_id' => 1,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            11 => [
                'id' => 12,
                'name' => 'Laptop',
                'vendor_id' => 1,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            12 => [
                'id' => 13,
                'name' => 'Laptop PC touch',
                'vendor_id' => 1,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            13 => [
                'id' => 14,
                'name' => 'HP ENVY 17t-ch000',
                'vendor_id' => 1,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            14 => [
                'id' => 15,
                'name' => 'HP Laptop',
                'vendor_id' => 1,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            15 => [
                'id' => 16,
                'name' => 'LED TV',
                'vendor_id' => 1,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            16 => [
                'id' => 17,
                'name' => ' MI 43 Inch P1 4K UHD android LED TV',
                'vendor_id' => 1,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            17 => [
                'id' => 18,
                'name' => 'MI 43 Inch',
                'vendor_id' => 1,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            18 => [
                'id' => 19,
                'name' => 'MI',
                'vendor_id' => 1,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            19 => [
                'id' => 20,
                'name' => 'MI P1',
                'vendor_id' => 1,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            20 => [
                'id' => 21,
                'name' => 'WFC-3F5-GDEL-XX (Inverter)',
                'vendor_id' => 1,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            21 => [
                'id' => 22,
                'name' => 'Inverter',
                'vendor_id' => 1,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            22 => [
                'id' => 23,
                'name' => 'WFC',
                'vendor_id' => 1,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            23 => [
                'id' => 24,
                'name' => 'Waxjambu GL710H',
                'vendor_id' => 1,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            24 => [
                'id' => 25,
                'name' => 'Waxjambu',
                'vendor_id' => 1,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            25 => [
                'id' => 26,
                'name' => 'GL710H',
                'vendor_id' => 1,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            26 => [
                'id' => 27,
                'name' => 'WPL02-C1',
                'vendor_id' => 1,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            27 => [
                'id' => 28,
                'name' => 'power bank',
                'vendor_id' => null,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            28 => [
                'id' => 29,
                'name' => 'mobile',
                'vendor_id' => null,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            29 => [
                'id' => 30,
                'name' => 'accessory',
                'vendor_id' => null,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            30 => [
                'id' => 31,
                'name' => 'men',
                'vendor_id' => null,
                'product_counts' => 2,
                'status' => 'Active',
            ],
            31 => [
                'id' => 32,
                'name' => 'wallet',
                'vendor_id' => null,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            32 => [
                'id' => 33,
                'name' => 'fashion',
                'vendor_id' => null,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            33 => [
                'id' => 34,
                'name' => 'girls',
                'vendor_id' => null,
                'product_counts' => 2,
                'status' => 'Active',
            ],
            34 => [
                'id' => 35,
                'name' => 'women',
                'vendor_id' => null,
                'product_counts' => 2,
                'status' => 'Active',
            ],
            35 => [
                'id' => 36,
                'name' => 'ear',
                'vendor_id' => null,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            36 => [
                'id' => 37,
                'name' => 'ear rings',
                'vendor_id' => null,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            37 => [
                'id' => 38,
                'name' => 'watch',
                'vendor_id' => null,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            38 => [
                'id' => 39,
                'name' => 'girl',
                'vendor_id' => null,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            39 => [
                'id' => 41,
                'name' => 'toy',
                'vendor_id' => null,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            40 => [
                'id' => 42,
                'name' => 'boys',
                'vendor_id' => null,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            41 => [
                'id' => 43,
                'name' => 'children',
                'vendor_id' => null,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            42 => [
                'id' => 44,
                'name' => 'adult',
                'vendor_id' => null,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            43 => [
                'id' => 45,
                'name' => 'anti-stress',
                'vendor_id' => null,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            44 => [
                'id' => 46,
                'name' => 'headphone',
                'vendor_id' => null,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            45 => [
                'id' => 47,
                'name' => 'bluetooth',
                'vendor_id' => null,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            46 => [
                'id' => 48,
                'name' => 'bag',
                'vendor_id' => null,
                'product_counts' => 6,
                'status' => 'Active',
            ],
            47 => [
                'id' => 49,
                'name' => 'bagpack',
                'vendor_id' => null,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            48 => [
                'id' => 50,
                'name' => 'smart',
                'vendor_id' => null,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            49 => [
                'id' => 51,
                'name' => 'Electronic device',
                'vendor_id' => null,
                'product_counts' => 4,
                'status' => 'Active',
            ],
            50 => [
                'id' => 52,
                'name' => 'Television',
                'vendor_id' => null,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            51 => [
                'id' => 53,
                'name' => 'white fachion',
                'vendor_id' => null,
                'product_counts' => 11,
                'status' => 'Active',
            ],
            52 => [
                'id' => 54,
                'name' => 'white fachion full',
                'vendor_id' => null,
                'product_counts' => 5,
                'status' => 'Active',
            ],
            53 => [
                'id' => 55,
                'name' => 'Furniture',
                'vendor_id' => null,
                'product_counts' => 6,
                'status' => 'Active',
            ],
            54 => [
                'id' => 56,
                'name' => 'Woman Dress',
                'vendor_id' => null,
                'product_counts' => 4,
                'status' => 'Active',
            ],
            55 => [
                'id' => 57,
                'name' => 'Woman Fashion',
                'vendor_id' => null,
                'product_counts' => 3,
                'status' => 'Active',
            ],
            56 => [
                'id' => 58,
                'name' => 'School bag',
                'vendor_id' => null,
                'product_counts' => 2,
                'status' => 'Active',
            ],
            57 => [
                'id' => 59,
                'name' => 'Pad',
                'vendor_id' => null,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            58 => [
                'id' => 60,
                'name' => 'Sanitary Pad',
                'vendor_id' => null,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            59 => [
                'id' => 61,
                'name' => 'Napkin',
                'vendor_id' => null,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            60 => [
                'id' => 62,
                'name' => 'Travel Bag',
                'vendor_id' => null,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            61 => [
                'id' => 63,
                'name' => 'Book',
                'vendor_id' => null,
                'product_counts' => 2,
                'status' => 'Active',
            ],
            62 => [
                'id' => 64,
                'name' => 'Card',
                'vendor_id' => null,
                'product_counts' => 2,
                'status' => 'Active',
            ],
            63 => [
                'id' => 65,
                'name' => 'Wireless',
                'vendor_id' => null,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            64 => [
                'id' => 66,
                'name' => 'Shirts',
                'vendor_id' => null,
                'product_counts' => 2,
                'status' => 'Active',
            ],
            65 => [
                'id' => 67,
                'name' => 'Kids',
                'vendor_id' => null,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            66 => [
                'id' => 68,
                'name' => 'T-shirt',
                'vendor_id' => null,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            67 => [
                'id' => 69,
                'name' => 'digital product',
                'vendor_id' => null,
                'product_counts' => 6,
                'status' => 'Active',
            ],
            68 => [
                'id' => 70,
                'name' => 'digital product feature',
                'vendor_id' => null,
                'product_counts' => 2,
                'status' => 'Active',
            ],
            69 => [
                'id' => 71,
                'name' => 'New Fashion',
                'vendor_id' => null,
                'product_counts' => 8,
                'status' => 'Active',
            ],
            70 => [
                'id' => 73,
                'name' => 'Electronics',
                'vendor_id' => null,
                'product_counts' => 8,
                'status' => 'Active',
            ],
            71 => [
                'id' => 74,
                'name' => 'group product',
                'vendor_id' => null,
                'product_counts' => 2,
                'status' => 'Active',
            ],
            72 => [
                'id' => 75,
                'name' => 'combo product',
                'vendor_id' => null,
                'product_counts' => 1,
                'status' => 'Active',
            ],
            73 => [
                'id' => 77,
                'name' => 'women\'s',
                'vendor_id' => null,
                'product_counts' => 1,
                'status' => 'Active',
            ],
        ]);

    }
}
